### ISSUE TITLE
MediaLab page down, help to run from the code

### ISSUE THREAD

**Issue by jonathankemp** [medialab/table2net#7]
Hey!

I have used the tool on MediaLab and found it very helpful for creating networks to use with Gephi from spreadsheets, exactly like you describe.
I was trying to do the same today and haven't been able to access the page on Medialab. I hope this is temporary.
Either way, would you mind explaining to me how to run the tool using the code you have posted here, or is that not possible?

Thanks,
Jonathan

PS sorry if 'Issue' is the wrong place to ask this question, I wasn't sure and am new to GitHub

**Comment by boogheta** [comment]
Hi @jonathankemp 
Is this the url you've been trying ? http://tools.medialab.sciences-po.fr/table2net/
If so, it was probably inaccessible temporarily due to a server fault during the summer, but it's back up and running, enjoy !

To run the tool from the code, you need to "clone" the repository using git on your local computer and serve the directory using any server software (apache, nginx, python -m SimpleHTTPServer, etc)
